#!/bin/sh

#
# Start (and daemonize) and stop the afrenewauth daemon for AliEn.
#
# by Dario Berzano <dario.berzano@gmail.com>
#
# This script is conform to the LSB specifications and it is compatible with
# the chkconfig custom header format.
#

#
# chkconfig header
#

# chkconfig: 2345 99 0
# description: afrenewauth is a daemonized script that automatically renews the
#              AliEn token and Grid proxy
# processname: afrenewauthd
# pidfile: /var/run/afrenewauthd.pid

#
# LSB header
#

### BEGIN INIT INFO
# Provides: afrenewauthd
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Short-Description: System-wide authentication keeper for AliEn
# Description: afrenewauth is a daemonized script that automatically renews the
#              AliEn token and Grid proxy
### END INIT INFO

# Source function library
if [ -r /lib/lsb/init-functions ]; then
  . /lib/lsb/init-functions
elif [ -r /etc/init.d/functions ]; then
  . /etc/init.d/functions
fi

# Get the configuration variables
if [ -r /etc/sysconfig/afrenewauthd ]; then
  . /etc/sysconfig/afrenewauthd
fi

[ -x $AFRENEWAUTHD_LOGFILE ] || exit 0

RETVAL=0
PID=$(cat "$AFRENEWAUTHD_PIDFILE")
PROG=afrenewauthd

start() {
  echo -n "Starting $PROG..."
  if [ ! "$PID" -eq "" ]; then
    kill -0 > /dev/null 2>&1
    if [ $? -eq 0 ]; then
      echo "done (already running)"
      return 0
    fi
  fi

  # Creates logfile writable by daemon and backups the previous one
  rm -f "$AFRENEWAUTHD_LOGFILE".0
  mv "$AFRENEWAUTHD_LOGFILE" "$AFRENEWAUTHD_LOGFILE".0
  touch "$AFRENEWAUTHD_LOGFILE"
  chown $AFRENEWAUTHD_USER "$AFRENEWAUTHD_LOGFILE"

  # Launches the daemon
  cd /tmp
  nohup "$AFRENEWAUTHD_PROG" -p "$AFRENEWAUTHD_PIDFILE" -l "$AFRENEWAUTHD_LOGFILE" -s $AFRENEWAUTHD_RENEW_SLEEP_SEC &
  RETVAL=$?

  [ $RETVAL -eq 0 ] && echo "done" || echo "failed"
  return $RETVAL
}

stop() {
  echo -n "Stopping $PROG..."
  if [ ! "$PID" -eq "" ]; then
    kill -15 "$PID"
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
      echo "done"
      rm -f "$AFRENEWAUTHD_PIDFILE"
    else
      echo "failed"
    fi
  else
    echo "failed (not running)"
  fi

  return $RETVAL
}

#
# Entry point
#

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  status)
    status afrenewauthd
    RETVAL=$?
  ;;
  restart|reload)
    # Restarts the daemon; results in a start if daemon wasn't running
    stop
    start
  ;;
  *)
     echo  "Usage: $0 {start|stop|status|restart|reload}"
     exit 1
  ;;
esac

exit $RETVAL
