#!/bin/bash

#
# Wrapper for synchronous staging via xrdstagetool.
#
# by Dario Berzano <dario.berzano@gmail.com>
#
# The difference with xrdstagetool is that the output (stdout) is captured to
# return the proper exit code on failure (1) or success (0).
#
# === USAGE ===
#
# afsynstg root://redir[:port]//stagepath/file/to/stage.ext
#
# === EXIT CODES ===
#
#  - 0 : success
#  - 1 : failure
#  - 2 : unknown!
#

# Load library functions
source `dirname $0`/aflib

# Entry point
if [ "$1" == "" ]; then
  exit 1
fi

# stderr is not redirected
TMPOUT=`mktemp /tmp/afsynstg-xrdstagetool-XXXXX`
xrdstagetool -d 1 "$1" > "$TMPOUT"

grep -q '^FAIL' "$TMPOUT"
if [ $? == 0 ]; then
  rm "$TMPOUT"
  exit 1
fi

grep -q '^OK' "$TMPOUT"
if [ $? == 0 ]; then
  rm "$TMPOUT"
  exit 0
fi

rm "$TMPOUT"
exit 2
